import type { EventItem } from '../types';

export const mockEvents: EventItem[] = [
  {
    id: 'evt-01',
    title: 'Build Weekend: 48h AI Hackathon',
    description:
      'Form a team on Friday night, ship an AI-powered prototype by Sunday afternoon. Mentors from local startups on hand all weekend, plus GPU credits for every team. Demos judged on usefulness, not polish.',
    category: 'Hackathon',
    startsAt: '2026-10-09T17:00:00.000Z',
    endsAt: '2026-10-11T16:00:00.000Z',
    location: { venue: 'The Foundry Co-working', address: '12 Market Street, 3rd Floor' },
    attendeeCount: 142,
    capacity: 160,
    organizerId: 'usr-04',
    tags: ['AI', 'Prototyping', 'Prizes'],
  },
  {
    id: 'evt-02',
    title: 'Founders & Coffee',
    description:
      'A relaxed Saturday-morning meetup for early-stage founders. No slides, no pitches — just honest conversations about hiring, fundraising and burnout over good coffee.',
    category: 'Networking',
    startsAt: '2026-10-03T08:30:00.000Z',
    endsAt: '2026-10-03T10:30:00.000Z',
    location: { venue: 'Grindhouse Café', address: '48 Riverside Walk' },
    attendeeCount: 36,
    capacity: 40,
    organizerId: 'usr-01',
    tags: ['Founders', 'Casual'],
  },
  {
    id: 'evt-03',
    title: 'Pitch Night: Seed Stage Edition',
    description:
      'Eight pre-seed and seed startups get five minutes each in front of a panel of angels and VCs. Live Q&A after every pitch, and audience vote for the crowd favourite.',
    category: 'Pitch Night',
    startsAt: '2026-10-15T18:00:00.000Z',
    endsAt: '2026-10-15T21:00:00.000Z',
    location: { venue: 'Innovation Hall', address: '1 University Avenue, Block C' },
    attendeeCount: 210,
    capacity: 250,
    organizerId: 'usr-03',
    tags: ['Fundraising', 'Angels', 'VC'],
  },
  {
    id: 'evt-04',
    title: 'Hands-on: Fine-tuning Small LLMs',
    description:
      'A practical workshop on fine-tuning open-weight language models on a laptop budget. Bring your own machine; we cover dataset prep, LoRA, evaluation and deployment.',
    category: 'Workshop',
    startsAt: '2026-10-20T14:00:00.000Z',
    endsAt: '2026-10-20T17:30:00.000Z',
    location: { venue: 'NeuralForge Lab', address: '77 Quantum Lane' },
    attendeeCount: 48,
    capacity: 50,
    organizerId: 'usr-02',
    tags: ['AI/ML', 'LLMs', 'Bring laptop'],
  },
  {
    id: 'evt-05',
    title: 'Accelerator Demo Day — Cohort 7',
    description:
      'Twelve startups graduate from the Launchpad accelerator and show what they built in 12 weeks. Investor-only session in the morning, open doors from 2pm.',
    category: 'Demo Day',
    startsAt: '2026-11-05T13:00:00.000Z',
    endsAt: '2026-11-05T18:00:00.000Z',
    location: { venue: 'Launchpad HQ', address: '200 Harbour Road' },
    attendeeCount: 320,
    capacity: 400,
    organizerId: 'usr-03',
    tags: ['Accelerator', 'Startups', 'Investors'],
  },
  {
    id: 'evt-06',
    title: 'Panel: Bootstrapping vs. Raising',
    description:
      'Three founders who went different routes — bootstrapped, angel-funded and VC-backed — debate what they would do differently. Moderated audience Q&A to close.',
    category: 'Panel',
    startsAt: '2026-10-22T17:30:00.000Z',
    endsAt: '2026-10-22T19:30:00.000Z',
    location: { venue: 'City Library Auditorium', address: '5 Civic Square' },
    attendeeCount: 95,
    capacity: 150,
    organizerId: 'usr-01',
    tags: ['Fundraising', 'Strategy'],
  },
  {
    id: 'evt-07',
    title: 'Tech Mixer: Devs × Designers',
    description:
      'An evening mixer to help developers and designers find co-founders and collaborators. Colour-coded name badges, lightning intros and snacks.',
    category: 'Networking',
    startsAt: '2026-10-29T18:30:00.000Z',
    endsAt: '2026-10-29T21:00:00.000Z',
    location: { venue: 'The Foundry Co-working', address: '12 Market Street, Rooftop' },
    attendeeCount: 118,
    capacity: 150,
    organizerId: 'usr-04',
    tags: ['Co-founders', 'Design', 'Engineering'],
  },
  {
    id: 'evt-08',
    title: 'Intro to Computer Vision with Python',
    description:
      'Beginner-friendly workshop covering image classification and object detection with open-source tools. Ideal for students and developers new to ML.',
    category: 'Workshop',
    startsAt: '2026-11-12T10:00:00.000Z',
    endsAt: '2026-11-12T13:00:00.000Z',
    location: { venue: 'Engineering Building, Lab 204', address: '1 University Avenue' },
    attendeeCount: 60,
    capacity: 60,
    organizerId: 'usr-02',
    tags: ['AI/ML', 'Python', 'Beginner'],
  },
  {
    id: 'evt-09',
    title: 'Climate Tech Hack Day',
    description:
      'A one-day sprint on energy, mobility and circular-economy challenges set by local climate startups. Winning team gets a pilot with a partner company.',
    category: 'Hackathon',
    startsAt: '2026-11-21T08:00:00.000Z',
    endsAt: '2026-11-21T20:00:00.000Z',
    location: { venue: 'Greenworks Studio', address: '31 Canal Street' },
    attendeeCount: 74,
    capacity: 100,
    organizerId: 'usr-05',
    tags: ['Climate', 'Sustainability', 'Prizes'],
  },
  {
    id: 'evt-10',
    title: 'Student Startup Pitch Night',
    description:
      'University teams pitch their side projects and startups to alumni founders. Five-minute pitches, practical feedback and a small grant for the winner.',
    category: 'Pitch Night',
    startsAt: '2026-11-18T17:00:00.000Z',
    endsAt: '2026-11-18T20:00:00.000Z',
    location: { venue: 'Student Union, Main Hall', address: '3 Campus Green' },
    attendeeCount: 130,
    capacity: 200,
    organizerId: 'usr-05',
    tags: ['Students', 'Feedback', 'Grants'],
  },
  {
    id: 'evt-11',
    title: 'Panel: Women Building in Deep Tech',
    description:
      'Founders and engineers from robotics, biotech and AI infrastructure share how they got started and what the ecosystem still gets wrong.',
    category: 'Panel',
    startsAt: '2026-12-02T17:30:00.000Z',
    endsAt: '2026-12-02T19:30:00.000Z',
    location: { venue: 'Innovation Hall', address: '1 University Avenue, Block A' },
    attendeeCount: 88,
    capacity: 120,
    organizerId: 'usr-01',
    tags: ['Diversity', 'Deep tech'],
  },
  {
    id: 'evt-12',
    title: 'SaaS Demo Day & Year-end Mixer',
    description:
      'Local SaaS startups demo new launches in short 3-minute slots, followed by a year-end mixer with founders, investors and operators.',
    category: 'Demo Day',
    startsAt: '2026-12-10T16:00:00.000Z',
    endsAt: '2026-12-10T21:00:00.000Z',
    location: { venue: 'Launchpad HQ', address: '200 Harbour Road' },
    attendeeCount: 185,
    capacity: 250,
    organizerId: 'usr-06',
    tags: ['SaaS', 'Launches', 'Mixer'],
  },
];
